services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: employee


  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8000:8080"
